### ISSUE TITLE
Improve handling of multimappers with STAR

### ISSUE THREAD

**Issue by sidorov-si** [ComputationalRegulatoryGenomicsICL/cageflow#15]
### Description of feature

Remove the limit on the number of mappings (n = 2) from the list of STAR options and add --outSAMmultNmax 1 --outMultimapperOrder Random to output only one mapping place (a random one among the best) for each read, independently of how many places it can be mapped to (if this number is no more than 10; if it's higher, then render the read unmapped).

**Comment by ferenckata** [comment]
this can be interesting as a strategy:
https://www.sciencedirect.com/science/article/pii/S0888754307002790?via%3Dihub#bib9

**Comment by sidorov-si** [comment]
I realised that we could combine the current option --outFilterMultimapNmax 2 (consider as mapped only reads that map to <= 2 places in the whole genome) with the planned options --outSAMmultNmax 1 --outMultimapperOrder Random  to choose one of the two mapping places at random (if they have the same score; if one prevails, then it will be chosen by design). In this way, we do not quantify repeats but still catch some signal from possible highly similar loci in paralogous genes.

**Comment by sidorov-si** [comment]
Additionally, consolidate container definitions for STAR.
