### ISSUE TITLE
multiple folders as input for input_reads.sh

### ISSUE THREAD

**Issue by ferenckata** [ComputationalRegulatoryGenomicsICL/cageflow#4]
### Description of feature

Add possibility in  input_reads.sh to read fastq files from the following structure:
fastq_folder/sample_1/sample1_R1.fastq
fastq_folder/sample_2/sample2_R1.fastq
...
fastq_folder/sample_N/sampleN_R1.fastq

currently it expects this structure:
fastq_folder/sample1_R1.fastq
fastq_folder/sample2_R1.fastq
...
fastq_folder/sampleN_R1.fastq

**Comment by sidorov-si** [comment]
What would be the benefit of placing each sample's FASTQ(s) in a separate directory? I can see one: if there are several FASTQs (for example, one per lane) for one read. Then, it would clarify the structure of the input data set.

**Comment by ferenckata** [comment]
well, that is the way I received the data so I assumed it might be common :)

**Comment by ferenckata** [comment]
btw, I added this issue to keep track of things. As a practice in groovy, I wrote an alternative script for this in nextflow language using file (path/**_R1*) syntax, I am testing it now and happy to discuss in a pull request

**Comment by sidorov-si** [comment]
Yes, this is a good reason :) Oh, wonderful! Yes, please, go ahead, and I'll be happy to discuss the result in the PR!

**Comment by ferenckata** [comment]
great, thank you!
I actually still don't have writing permissions, could you please update that?

**Comment by sidorov-si** [comment]
Oh, sorry, fixed!

**Comment by ferenckata** [comment]
This is done, closing this issue now.
