### ISSUE TITLE
containerize local modules

### ISSUE THREAD

**Issue by ferenckata** [ComputationalRegulatoryGenomicsICL/cageflow#5]
### Description of feature

samtools, dplyr, purrr, etc. in local modules are currently expected to be available globally. Would be nicer to assign their containers to the processes

**Comment by sidorov-si** [comment]
Actually, each local module has a container assigned to it in [conf/modules.config](https://github.com/ComputationalRegulatoryGenomicsICL/customcageq/blob/dev/conf/modules.config). But I will need to unify it with other modules which have container definitions within their `.nf` files.

**Comment by ferenckata** [comment]
Yes, I was just confused when looking around, as the nf-core files have them defined within main.nf. Later I found it in the modules.config, but I agree that unifying would look nicer. Probably not a priority, but also quite easy to do.

**Comment by sidorov-si** [comment]
I agree, let me assign it to myself.

**Comment by ferenckata** [comment]
I think it is not a priority anymore, I close it now.
