### ISSUE TITLE
extend config so that all parameters can be defined there

### ISSUE THREAD

**Issue by ferenckata** [ComputationalRegulatoryGenomicsICL/cageflow#6]
### Description of feature

Extend and organize config

**Comment by sidorov-si** [comment]
Could you please provide more details? 

Do you mean that it would be useful to have a YAML parameter file for a pipeline run, similar to what nf-core pipelines have? -- See, for example, https://nf-co.re/scrnaseq/2.7.0/docs/usage (section "Running the pipeline"). If so, I totally agree, -- it would be very convenient.

**Comment by ferenckata** [comment]
Yes, like params.yaml in the resource you linked.
It is probably not a priority, but quite easy to do. I can help with adding this.

**Comment by sidorov-si** [comment]
Yup, I totally agree that it would be very convenient to have (and implementing it earlier would speed up future work). Let me assign it to myself, so that you could concentrate on testing the pipeline and implementing CAGEr-related modules in coordination with Damir.
